// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJ6CcRQNuMjqj4-HJ90hMsJcPPd1lfOA',
    appId: '1:516571161592:web:3afacdb2fc171feb12ac0d',
    messagingSenderId: '516571161592',
    projectId: 'upload-pdf-e2ff0',
    authDomain: 'upload-pdf-e2ff0.firebaseapp.com',
    storageBucket: 'upload-pdf-e2ff0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZnXGYkMgHWR6Im1Pml5RXH1tkkfPWyE',
    appId: '1:516571161592:android:f73e17c22321d90e12ac0d',
    messagingSenderId: '516571161592',
    projectId: 'upload-pdf-e2ff0',
    storageBucket: 'upload-pdf-e2ff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjpVByyViuVgRHVI0bgM-ZaTJlko-JTdU',
    appId: '1:516571161592:ios:e34c123df3a1e8c812ac0d',
    messagingSenderId: '516571161592',
    projectId: 'upload-pdf-e2ff0',
    storageBucket: 'upload-pdf-e2ff0.appspot.com',
    iosClientId: '516571161592-snc9mmraskj3eb6la57v2h8ok3dlv1e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdfUpload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjpVByyViuVgRHVI0bgM-ZaTJlko-JTdU',
    appId: '1:516571161592:ios:e34c123df3a1e8c812ac0d',
    messagingSenderId: '516571161592',
    projectId: 'upload-pdf-e2ff0',
    storageBucket: 'upload-pdf-e2ff0.appspot.com',
    iosClientId: '516571161592-snc9mmraskj3eb6la57v2h8ok3dlv1e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdfUpload',
  );
}
